name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    environment: env
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file fleet-helper.dockerfile --tag yvolchkov/tesla-fleet-helper:$(date +%s) --tag yvolchkov/tesla-fleet-helper:latest
    - name: push to the registry
      run: |
        docker push yvolchkov/tesla-fleet-helper:latest
